### ISSUE TITLE
Tabela de Pontos de Complexidade Intrínseca no CDD

### ISSUE THREAD

**Issue by guilsilva** [claudiooliveirazup/documentacao-cartao-branco#13]
No link: https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/leitura-obrigatoria-design-codigo/0-0-1.2-cognitive-driven-development.md

Na tabela 1 do tópico "Como adotar Cognitive Driven Development" não deveria ter uma linha explicando "Acoplamento Contextual"? No texto é mencionado que _acoplamento contextual e acoplamento com tecnologias transversais são novas categorias_, mas só existe a categoria de acoplamento com tecnologias transversais na tabela.

**Comment by albertotavareszup** [comment]
Opa, obrigado pela dica! Corrigido!
