### ISSUE TITLE
Trocar bad request por unprocessable entity no requisito 3 da Casa do Código

### ISSUE THREAD

**Issue by Lds20k** [claudiooliveirazup/documentacao-cartao-branco#15]
Requisito: [Casa do Código 003](https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/treino-casa-do-codigo/0-0-3-email-autor-unico.md)

Trocar o _bad request_(400) para _unprocessable entity_(422), pois é uma regra de negocio e não uma requisição mal feita.

**Comment by luramarchanjozup** [comment]
@Lds20k ajuste feito, muito obrigado pela issue!
