### ISSUE TITLE
Link "COMO ALBERTO FARIA ESSE CÓDIGO?" está encaminhando para "[novo autor] cadastro e validacao de email duplicado"

### ISSUE THREAD

**Issue by thaismathias** [claudiooliveirazup/documentacao-cartao-branco#18]
Alterar link.

**Comment by luramarchanjozup** [comment]
Olá @thaismathias tudo bem? Em qual material se encontra o problema, por favor?

**Comment by thaismathias** [comment]
https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/treino-casa-do-codigo/0-0-5-criar-um-novo-livro.md

**Comment by luramarchanjozup** [comment]
@thaismathias ajuste feito, muito obrigado por avisar!
