### ISSUE TITLE
Link sobre proteção das bordas "indisponível"

### ISSUE THREAD

**Issue by thaismathias** [claudiooliveirazup/documentacao-cartao-branco#19]
Link:https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/treino-casa-do-codigo/0-0-9-comeco-fluxo-pagameno-parte-1.md

No sexto tópico de informação de suporte tem apenas um link, acredito que deveria ter dois. "Confira uma explicação sobre ele **AQUI** e depois **AQUI**"

**Comment by luramarchanjozup** [comment]
@thaismathias ajuste feito, muito obrigado pela sugestão!
