### ISSUE TITLE
Referenciar o Feing

### ISSUE THREAD

**Issue by Lds20k** [claudiooliveirazup/documentacao-cartao-branco#20]
Referenciar o Feing no README.MD para o e-commerce e no [0-0-0-setup.md](https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/treino-mercado-livre/0-0-0-setup.md)

**Comment by luramarchanjozup** [comment]
@Lds20k ajuste feito, muito obrigado pela sugestão!
