### ISSUE TITLE
Setup do ecommerce é o setup da Casa do Código

### ISSUE THREAD

**Issue by Lds20k** [claudiooliveirazup/documentacao-cartao-branco#22]
[0-0-0-setup.md](https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/treino-mercado-livre/0-0-0-setup.md)

**Comment by luramarchanjozup** [comment]
@Lds20k poderia detalhar a sugestão, por favor?

**Comment by Lds20k** [comment]
@luramarchanjozup O arquivo de setup MarkDown do ecommerce é o mesmo da casa do código

**Comment by luramarchanjozup** [comment]
@Lds20k ajuste feito, muito obrigado!
