### ISSUE TITLE
Retirar o Spring Security da lista de tecnologias do ecommerce

### ISSUE THREAD

**Issue by Lds20k** [claudiooliveirazup/documentacao-cartao-branco#23]
[README.md](https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/README.md)

**Comment by luramarchanjozup** [comment]
@Lds20k poderia detalhar a sugestão, por favor?

**Comment by Lds20k** [comment]
@luramarchanjozup conforme foi pedido em um dos encontros, o senhor me pediu para abrir um issue para retirada do spring security da lista de tecnologias, porem no decorrer dos requisitos foi visto que era necessário.

**Comment by luramarchanjozup** [comment]
@Lds20k perfeito, portanto irei manter o documento e fechar a issue, muito obrigado!
