### ISSUE TITLE
Adicionar referência ao arquivo docker-compose.yaml

### ISSUE THREAD

**Issue by marcoscoutozup** [claudiooliveirazup/documentacao-cartao-branco#27]
Bom dia pessoal! Acho que seria interessante no tópico [001.setup_docker_compose.md](https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/proposta/001.setup_docker_compose.md), mais específico na sessão [Rodando nossas dependências](https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/proposta/001.setup_docker_compose.md#rodando-nossas-depend%C3%AAncias), acrescentar a referência ao arquivo docker-compose.yaml para fazer a cópia.

**Comment by luramarchanjozup** [comment]
@marcoscoutozup muito obrigado pela issue! Já existe um link conforme imagem:

![image](https://user-images.githubusercontent.com/68293469/96587666-fd6d1900-12b8-11eb-9a35-79ca65652af6.jpg)

Uma dúvida esse link é suficiente ou devemos adicionar em outras partes do documento?

**Comment by marcoscoutozup** [comment]
@luramarchanjozup É suficiente sim!! Eu passei pelo link sem perceber hehehe. Obrigado!!
