### ISSUE TITLE
Imagem errada em Criando escopos no Keycloak

### ISSUE THREAD

**Issue by thaismathias** [claudiooliveirazup/documentacao-cartao-branco#32]
link: https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/informacao_suporte/keycloak-scope.md

Após "Encontre e selecione o escopo criado na seção Default Client Scopes e **clieque** em Add selected, conforme imagem abaixo:" está a imagem errada. Está a mesma imagem de Clients ->Edit.

Aproveitando: "Clique" está escrito errado.

**Comment by luramarchanjozup** [comment]
@thaismathias ajuste feito, muito obrigado!
