### ISSUE TITLE
Imagem do artigo sobre CDD não sendo exibida

### ISSUE THREAD

**Issue by arielalvesdutrazup** [claudiooliveirazup/documentacao-cartao-branco#8]
Link: https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/leitura-obrigatoria-design-codigo/0-0-1.2-cognitive-driven-development.md

A imagem deveria ser exibida logo abaixo do trecho: *Embora tal código possa aumentar a complexidade cognitiva do software, sugerimos não considerá-los como PCI, porque eles, em geral, não são alterados dentro da construção da lógica de negócios.*

**Comment by arielalvesdutrazup** [comment]
Também tem uma correção de escrita em: *Tais clases geralmente são aquelas conhecidas como Controllers e Services*. Corrigir para *classes*.

**Comment by luramarchanjozup** [comment]
> Link: https://github.com/claudiooliveirazup/documentacao-cartao-branco/blob/master/leitura-obrigatoria-design-codigo/0-0-1.2-cognitive-driven-development.md
> 
> A imagem deveria ser exibida logo abaixo do trecho: _Embora tal código possa aumentar a complexidade cognitiva do software, sugerimos não considerá-los como PCI, porque eles, em geral, não são alterados dentro da construção da lógica de negócios._

Muito obrigado por avisar, acredito que no PR https://github.com/claudiooliveirazup/documentacao-cartao-branco/pull/9 foi arrumado, poderia verificar por favor

**Comment by luramarchanjozup** [comment]
> Também tem uma correção de escrita em: _Tais clases geralmente são aquelas conhecidas como Controllers e Services_. Corrigir para _classes_.

Correção efetuada, muito obrigado @arielalvesdutrazup
